### ISSUE TITLE
Failed to launch the demo

### ISSUE THREAD

**Issue by mikaelmorvan** [wundergraph/wundergraph-demo#2]
Hi,

I'm trying to launch the demo and I've got some bugs :

1) The docker-compose.yml file don't launch if I don't have a version tag on top of it

2) After installing wunderctl, I'm trying to launch it in the .wundergraph directory and nothing happens :
I've got the following json message :
`{"level":"info","ts":"2021-10-21T18:13:08.872326848+02:00","msg":"starting WunderNode","version":"0.26.3","commit":"826ec6a9b4aebc8b7ad395ec5e18e8ebcdf7e24f","date":"2021-10-21T08:02:37Z","builtBy":"ci"}
{"level":"info","ts":"2021-10-21T18:13:08.915413044+02:00","msg":"api config: file polling","config_file_name":"wundergraph.config.json"}
{"level":"debug","ts":"2021-10-21T18:13:08.919160912+02:00","msg":"Analytics config","enable":false}
{"level":"debug","ts":"2021-10-21T18:13:08.919239049+02:00","msg":"filePollConfig - config file not found, retrying in 5s","config_path":"wundergraph.config.json"}
{"level":"fatal","ts":"2021-10-21T18:13:09.066358235+02:00","msg":"Config Bundler: initial build failed","bundler":"hooks","outFile":"/home/mikaelmorvan/.wundergraph/config/d3VuZGVyZ3JhcGguaG9va3MudHPUHYzZjwCyBOmACZjs-EJ-/hooks.js","errors":[{"PluginName":"","Text":"Could not resolve \"fastify\" (mark it as external to exclude it from the bundle)","Location":{"File":"generated/wundergraph.hooks.configuration.ts","Namespace":"","Line":1,"Column":20,"Length":9,"LineText":"import Fastify from \"fastify\";","Suggestion":""},"Notes":null,"Detail":null}]}`

3) When I launch the nextjs frontend, I've got an error on the webpage
`Unhandled Runtime Error
TypeError: Failed to fetch`

I'm on Ubuntu 18.04 by the way

Thanks for you help
  Mikaël

**Comment by jensneuse** [comment]
Looks like you did not install the dependencies in the .wundergraph folder. ("Could not resolve "fastify")
Try `cd .wundergraph` and then `npm i` or `yarn`, then try it again.
If it keeps failing, let me know the console output.
Otherwise, would be helpful to know if you're able to run the demo.

Regarding the docker-compose, could you open a PR with the fixed file or paste the correct content here? Thanks!
